### ISSUE TITLE
Unable to mount developer disk image on iOS 8.4

### ISSUE THREAD

**Issue by haxpor** [phonegap/ios-deploy#155]
I have successfully use ios-deploy on iOS 8.2 (12D508) as it's my another device, but failed to do so on iOS 8.4 (12H143) when it entered the Debugging Phase as it shout as below.

Here is my system info
**sw_vers**: `10.10.4`
**ios-deploy**: `1.7.0`
**xcodebuild -version**:
`Xcode 6.4
Build version 6E35b`
**xcode-select --print-path**:
`/Applications/Xcode.app/Contents/Developer`
**gcc --version**:

    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
    Target: x86_64-apple-darwin14.4.0
    Thread model: posix
**lldb --version**:
`lldb-330.0.48`

    ------ Debug phase ------
    Starting debug of iPod Touch 5G 'iPod touch' (46feafc8d86d42adac26bab589b46e26540568d0) connected through USB...
    [  0%] Looking up developer disk image
    2015-07-03 12:43:10.476 ios-deploy[35434:105392] [ !! ] Unable to mount developer disk image. (e8000033)`

I check at the path of developer disk image, and it's there.

**Comment by shazron** [comment]
I just ran it with iOS 8.4, and it installed fine, so not sure exactly how to debug this.

Check Xcode -> Window -> Devices, and whether Xcode has pulled the debug symbols of your device. It may take a minute or so.

**Comment by haxpor** [comment]
@shazron I checked it, it's there. See the log after I executed ios-deploy command.

Log (from Device window of Xcode)
    ...
    Jul  3 21:30:27 iPod-touch mobile_installation_proxy[341] <Warning>: LaunchServices: Please include the kCFBundleIdentifierKey in the options dictionary when installing an app.
    Jul  3 21:30:27 iPod-touch mobile_installation_proxy[341] <Warning>: LaunchServices: installing app with unknown bundleID
    Jul  3 21:30:27 iPod-touch installd[342] <Notice>: 0x389000 -[MIClientConnection _doBackgroundInstallationForPath:withOptions:completion:]: Install of "/var/mobile/Media/PublicStaging/App - Fast Build.app" type Developer requested by mobile_installation_proxy (pid 341)
    Jul  3 21:30:28 iPod-touch installd[342] <Notice>: 0x389000 -[MIInstaller performInstallationWithError:]: Installing <MIInstallableBundle ID=com.something.App; Version=0.796.4.0, ShortVersion=(null)>
    Jul  3 21:30:28 iPod-touch profiled[271] <Notice>: (Note ) MC: Provisioning profiles changed
    Jul  3 21:30:28 iPod-touch installd[342] <Error>:  SecTrustEvaluate  [leaf CriticalExtensions IssuerCommonName]
    Jul  3 21:30:28 iPod-touch SpringBoard[42] <Warning>: Killing com.something.App for termination assertion
    Jul  3 21:30:28 iPod-touch pkd[109] <Warning>: releasing plug-in hold 20076BE0-7E7F-4412-83BE-843B35D7140A for dead client pid 42
    Jul  3 21:30:29 iPod-touch installd[342] <Notice>: 0x389000 -[MIInstallableBundle _refreshUUIDForContainer:withError:]: Data container for com.something.App is now at /private/var/mobile/Containers/Data/Application/95EC1136-E331-4BC6-89F0-7F736DCA161C
    Jul  3 21:30:29 iPod-touch installd[342] <Notice>: 0x389000 -[MIContainer makeContainerLiveReplacingContainer:withError:]: Made container live for com.something.App at /private/var/mobile/Containers/Bundle/Application/B389B7C1-9D01-4400-9A68-35910ABA48FC
    Jul  3 21:30:29 iPod-touch installd[342] <Notice>: 0x389000 -[MIInstaller performInstallationWithError:]: Staging: 0.05s; Waiting: 0.00s; Installation: 1.23s; Overall: 1.28s
    Jul  3 21:30:29 iPod-touch lsd[74] <Warning>: LaunchServices: Updating identifier store
    Jul  3 21:30:29 iPod-touch syncdefaultsd[507] <Notice>: (Note ) marked "com.me.keyvalueservice" topic as "opportunistic" on <APSConnection: 0x15e82420>
    Jul  3 21:30:30 iPod-touch SpringBoard[42] <Warning>: Installed apps did change.
	Added: {(
	)}
	Removed: {(
	)}
	Modified: {(
	    "com.something.App"
	)}

**Comment by haxpor** [comment]
@shazron After I shutdown the phone, and start it over, it works now. Thanks.

**Comment by saramburke** [comment]
I am seeing the same issue on my iPad mini with iOS 8.4 (12H143). This issue did not occur for 8.2. Restarting the iPad did not resolve the issue for me. I attempted to debug, and all the paths seem valid; for example, the image path /Applications/Xcode6.4.0.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/8.4 (12H141)/DeveloperDiskImage.dmg does in fact exist. Everything else seems normal but then the return code is negative, hence the resulting error message. 

I am trying this with a simple iOS Swift app, literally so simple that I created the app from the iOS Xcode target and built it without adding anything, and the error  "Unable to mount developer disk image" still occurs (i.e. the error occurs no matter what app I try to use) when I try to install & launch it with ios-deploy. 

I triple checked that all my stuff is correct (xcode-select points to Xcode 6.4, app path is valid, etc.), and the app actually gets installed successfully, it's just that the debug phase fails with the error message "Unable to mount developer disk image" (since mount_developer_image() is only called for lldb setup, not app install). 

Since others were able to resolve this error by restarting their devices, can someone tell me what contributing factors might be here with respect to restarting the device? What gets reset after a device restart that might cause this issue to resolve itself? What types of things cause this issue to manifest in the first place? I could not resolve the error with a device restart, so clearly something is missing for me. 

My system info is very similar to the original poster, but here’s the info anyway:

**sw_vers:** 10.10.3
**ios-deploy:** 1.7.0
**xcodebuild -version:** Xcode 6.4 Build version 6E35b
**xcode-select —print-path:** /Applications/Xcode6.4.0.app/Contents/Developer
**lldb --version:** lldb-330.0.48

**Comment by shazron** [comment]
@saramburke try running it with the "--verbose" flag to see if there are any clues in the output

**Comment by saramburke** [comment]
I tried running with --verbose and there is actually no difference in
output.
This is the command I used:

./ios-deploy --debug --bundle $MYAPP --verbose


All the output I get for the debug phase is:

------ Debug phase ------

Starting debug of J85AP 'ah-sburke1-maci_ipad1' <device_id>) connected
through USB...

2015-08-17 13:29:24.761 ios-deploy[7903:207374] [ !! ] Unable to locate
DeveloperDiskImage.dmg. This probably means you don't have Xcode installed,
you will need to launch the app manually and logging output will not be
shown!


The output is very misleading, as I have several versions of Xcode
installed. Perhaps the output could be changed to indicate what other
things could cause this issue.

I have tried resetting my iPad, then upgrading to iOS 9 beta, and seeing
the same result.


This is completely blocking me from using the tool :( Any other suggestions?




On Fri, Aug 14, 2015 at 10:19 PM, Shazron Abdullah <notifications@github.com
> wrote:

> @saramburke <https://github.com/saramburke> try running it with the
> "--verbose" flag to see if there are any clues in the output
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/ios-deploy/issues/155#issuecomment-131280778>
> .
>



-- 

------------------------------------
Sara.M.Burke@gmail.com
(774) 284-0176

**Comment by saramburke** [comment]
I tried running with --verbose and there is actually no difference in
output.
This is the command I used:

<pre>./ios-deploy --debug --bundle $MYAPP --verbose</pre>

All the output I get for the debug phase is:

<pre>
Starting debug of J85AP 'ah-sburke1-maci_ipad1' <device_id>) connected
through USB...

2015-08-17 13:29:24.761 ios-deploy[7903:207374] [ !! ] Unable to locate
DeveloperDiskImage.dmg. This probably means you don't have Xcode installed,
you will need to launch the app manually and logging output will not be
shown!
</pre>

The output is very misleading, as I have several versions of Xcode
installed. Perhaps the output could be changed to indicate what other
things could cause this issue.

I have tried resetting my iPad, then upgrading to iOS 9 beta, and seeing
the same result.


This is completely blocking me from using the tool :( Any other suggestions?

**Comment by shazron** [comment]
@saramburke I've prepared a test branch for this issue with verbose logging.
Install using:
`npm install git+https://github.com/phonegap/ios-deploy.git#issue-155 -g`

Then use the --verbose flag. This should show what paths the tool is trying to find the image from.
