### ISSUE TITLE
Lack of attribution in error.h

### ISSUE THREAD

**Issue by samdmarshall** [phonegap/ios-deploy#162]
Hi, it has come to my attention that you are using my list of error codes that was reverse engineered from the MobileDevice framework. You reference my implementation of this [here](https://github.com/phonegap/ios-deploy/blob/master/errors.h#L12-L169) but do not provide attribution for said list. 

Since I was the first person to publish the full list of error codes and respective constants for them, i'd like proper attribution for this and for your license file to be updated to reflect the usage of my 3-clause BSD code in addition to releasing under GPL v3.

Thank you!

**Comment by Smilediver** [comment]
Hi, sorry for this, no bad intentions. :) Please, check the following commit and let me know if it gives proper attribution, and if not, let me know what I should change.

https://github.com/Unity-Technologies/ios-deploy/commit/5eb12202b29216e9242a9f6048aeffae7a177c6a

**Comment by samdmarshall** [comment]
Hi, it still doesn't follow the terms of my license. Please see the [first clause](https://github.com/samdmarshall/SDMMobileDevice/blob/master/LICENSE#L6) with respects to what you must update. Thanks.

**Comment by shazron** [comment]
I'm not a lawyer so this is not legal advice, but from my interpretation of this is...

@smilediver since you are the author/copyright owner of the rest of errors.h, it might be simple to change the license of the whole file to BSD, and add the copyrights for you and @samdmarshall 

Also keeping in mind guidelines from section 2.3 of https://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html

**Comment by Smilediver** [comment]
Added full license text: https://github.com/Unity-Technologies/ios-deploy/commit/2c9ea8f16ef1aa251e4cfa5f41d9cab8d088c57a

**Comment by samdmarshall** [comment]
Thank you, it is much appreciated.
