### ISSUE TITLE
Can't pass in command line args to the iOS application

### ISSUE THREAD

**Issue by shazron** [phonegap/ios-deploy#250]
This is due to the patch in v1.8.7. See #240.

From @dot-asm:
https://github.com/phonegap/ios-deploy/issues/240#issuecomment-247038519
```
While fixing the crash this modification made it impossible to pass command line arguments to ios application. The lldb.py should read

    if len(args) > 1:
        args_arr = shlex.split(args[1])
    else:
        args_arr = shlex.split('{args}')
instead of

    if len(args) > 1:
        args_arr = shlex.split(args[1] and args[1] or '{args}')
```

**Comment by pMaske** [comment]
@shazron I am using version 1.9.2 of iOS-Deply and can still repro the issue. Can you confirm if this has been been fixed already.
The command I am using is:
ios-deploy --debug --bundle `path to app`  --args 'true 1968'

The app my I deploying is built in release mode, not sure if it matters.

Can you please advise?

**Comment by dot-asm** [comment]
I for one am using 2.0.0 and pass arguments all the time... It's not top of the master branch though, had no problems, saw no need to update...

**Comment by pMaske** [comment]
@dot-asm is the syntax correct

>ios-deploy --debug --bundle path to app --args 'true 1968'

**Comment by dot-asm** [comment]
Looks right. I mean similar one works for me [with 2.0.0].

**Comment by pMaske** [comment]
@dot-asm I used npm to install ios-deploy and it is not detecting ios-deploy to be outdated. How did you install 2.0.0?

**Comment by dot-asm** [comment]
> How did you install 2.0.0?

I just "git checkout"-ed this repository and compiled source code myself. BTW, I'm not actually that fluent MacOS user, so I don't even know what npm is. But if it's some kind of community repository thing, then question would be how do *they* maintain ios-deploy source. The bug in question has been fixed in this repository, but they might have failed to pick up the fix for some reason. I'm not saying that they did, but formally speaking that's where one should start asking this kind of questions, at binary provider's source. Unless you just compile it yourself ;-)
