### ISSUE TITLE
Running app on iOS device fails

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/ios-deploy#39]
Running the following command "cordova run ios" to deploy app directly to iOS device.

The application builds successfully but has problems when trying to copy it over to device.  On the "VerifyingApplication" step, getting following error: "AMDeviceInstallApplication failed: 0xE8008016: Unknown error."

**Comment by asharif** [comment]
Getting similar error:

[ 70%] VerifyingApplication
AMDeviceInstallApplication failed: 0xE8008016: Unknown error.


Doesn't seem to happen all the time.  Seems like it happens when I'm running it back to back.  It does seem like something takes a bit to exit.  I'm not familiar with lldb.  I did a ps -A | grep lldb and didn't see any processes running.  I'm running it like this:

ios-deploy -b bin/App.ipa

**Comment by shazron** [comment]
You run it against the .app, not the .ipa. Unpack the .ipa (it's just a zip file)

**Comment by asharif** [comment]
[ 70%] VerifyingApplication
AMDeviceInstallApplication failed: 0xE8008016: Unknown error.

same error:

ios-deploy -b bin/App.app

**Comment by asharif** [comment]
My mistake.  Please discard.  For some reason I didn't realize it was detecting the phone through wi-fi instead of USB.  It was not detecting the right phone!  Please disregard!

**Comment by irthos** [comment]
I'm getting this, too..
AMDeviceInstallApplication failed: 0xE8008016: Unknown error.
with an iPhone 4 / ios7

Simulator works but only as far back as 4S.

**Comment by peacemoon** [comment]
This has something to do with provisioning profile and not related to ios-deploy 
See here: http://stackoverflow.com/questions/11279352/error-0xe8008016

**Comment by shazron** [comment]
See: https://github.com/phonegap/ios-deploy/blob/7ac9cdb10742a2b1d1855d7a70d684e4e062278d/errors.h#L195 (thanks to @Smilediver)
